### GET products
GET  http://localhost:8000/products

### GET product by id
GET  http://localhost:8000/products/6

### POST product
POST http://localhost:8000/products
Content-Type: application/json

{
    "title": "HyperX",
    "price": 150
}

### PUT product
PUT http://localhost:8000/products/8
Content-Type: application/json

{
    "title": "HyperX",
    "price": 444
}

### DELETE product
DELETE http://localhost:8000/products/11


### GET products by price
GET http://localhost:8000/products?min_price=0&max_price=500
